SERPER_API_KEY: "3c6567565f9020d0b03d2e768b18d1eac9b67fa7"
OPENAI_API_KEY: "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"
# OPENAI_API_BASE: "https://ahgrz1vlg0zd9i-8000.proxy.runpod.net/v1"
# OPENAI_MODEL_NAME: "Meta-Llama-3-8B-Instruct"